service: riotinto-backend

provider:
  name: aws
  runtime: nodejs16.x # Node JS version
  memorySize: 512
  timeout: 30
  stage: ${opt:stage, 'development'} # serverless deploy --stage development
  environment:
    NODE_ENV: ${opt:stage, self:provider.stage, 'development'}
  region: ap-south-1 # AWS region   # new profile
  # region: us-west-1 # AWS region # current working
 
# plugins:
#   - serverless-plugin-typescript
 
functions:
  api:
    handler: app.handler
    events:
      - http: ANY {proxy+}
      - http: ANY /
package:
  include:
    - src/**/*.ejs



 