const { forgotPasswordController, sendOtp, loginController, registerController, updateUserController, updateProfileController } = require("../controllers/authController");
const express = require('express');
const router = express.Router();
router.post("/register", registerController);
router.post("/updateUser", updateUserController);
router.post("/login", loginController);
router.post("/forgot-password", forgotPasswordController);
router.post("/sent-otp", sendOtp);
router.put("/profile", updateProfileController);
module.exports = router;
